# Plugins
plugins:
- jekyll-sitemap
safe: false

# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENSE.txt', 'CNAME']


# Site Settings
title: "BCC2020"
email: "bcc2020-org@lists.galaxyproject.org"
description: "BCC2020 brings together the Galaxy Community Conference and Bioinformatics Open Source Conference to meet jointly in Toronto, Ontario, Canada."
baseurl: ""
url: "https://bcc2020.github.io"
permalink: "/blog/:title"
googleAnalyticsTrackingId: ""
googleAnalyticsSiteUrl: ""
siteVerification: ""

# Organizer Info
organizerName: "BOSC and Galaxy"
organizerAlternateName: ""
organizerDescription: "Bioinformatics Open Source Conference and Galaxy Community Conference join together in 2020 in Toronto, Canada for the first Bioinformatics Community Conference."
organizerEmail: ""
organizerLogo: "/img/seo/organizer-logo.png"
organizerLink: "#"

# Head
metaKeywords: "event, bioinformatics, conference, workflows, programming, research, science, developers, toronto, bosc, galaxy"
twitterAccount: ""
socialImageSrcTwitter: "/img/seo/sharing-twitter.png"
#socialImageSrcFacebook: "/img/seo/sharing-facebook.png"

# Link to EasyChair?
abstractSubmitUrl: "/submit/"

# Navigation
navigationLinks:
 - {permalink: "/", text: "Home"}
 - {permalink: "/about/", text: "About"}
 - {permalink: "/news/", text: "News"}
 - {permalink: "/submit/", text: "Submit"}
 - {permalink: "/schedule/", text: "Schedule"}
 - {permalink: "/location/", text: "Location"}
 - {permalink: "/cofest/", text: "CoFest"}
 - {permalink: "/partners/", text: "Partners"}
bottomNavigationLinks:
 - {link: "/submit/", text: "Submit an abstract"}
rightNavigationButtons:
 - {link: "/submit/", text: "Submit an abstract"}

# Hero Block
heroImage: "hero.jpg"
heroTitle: "Bioinformatics Community Conference 2020<br> <typeout>"
eventDate: "July 18-21, 2020"
heroButtons:
 - {link: "#", text: "Galaxy Community Conference (GCC)", logo: "/img/organizers/galaxy_project_logo_blue.png"}
 - {link: "#", text: "Bioinformatics Open Source Conference (BOSC)", logo: "/img/organizers/bioinformatics-open-source-conference-banner.png"}

# About Block
aboutTitle: "BCC2020"
aboutUs: "With two days of training, a two day meeting, and four days of intense collaboration, BCC2020 is packed full of joint & parallel sessions, keynotes, poster & demo sessions, birds-of-a-feather, and social events. BCC2020 is hosted by the Ontario Institue for Cancer Research and will be at Victoria University on the University of Toronto Campus."
aboutBlock:
 - {title: "Training", image: "workshop.jpg", text: "Two days of training workshops providing hands-on experience with experts."}
 - {title: "Conference", image: "conference.jpg", text: "The main conference. Interact and share research results and ideas in open source bioinformatics and Galaxy." }
 - {title: "CoFest", image: "hackathon.jpg", text: "A two to four day unstructuered session to collaboratively work on code, documentation, training materials, and challenging analysis problems and use cases." }

# Statistic Block
statisticBlockImage: "statistic.jpg"
statisticBlock:
 - {count: "350", specialCharacter: "+", info: "attendees", detail: "from everywhere"}
 - {count: "48", specialCharacter: "+", info: "hours", detail: "of programming"}
 - {count: "20", specialCharacter: "+", info: "speakers", detail: "from country and beyond"}
 - {count: "4", specialCharacter: "", info: "made up facts", detail: "replace these later!!"}

# Latest News Block
latestNewsTitle: "News"
latestNewsCount: 2

# Rockstar Speakers Block
rockstarSpeakersImage: "rockstar-speakers.jpg"
rockstarSpeakersCount: 4
rockstarSpeakersTitle: "Keynote Speakers"
rockstarSpeakersButtonText: "See all speakers"

# Location Block
locationBlockTitle: "Location"
eventLocationName: "Victoria University"
eventLocationLink: "https://studentlife.utoronto.ca/hello/directions"
eventStreetAddress: "73 Queen Park's Crescent #106"
eventAddressLocality: "Toronto"
eventAddressLocalityRegion: "Ontario"
eventPostalCode: "M5S 1K7"
eventAddressCountry: "Canada"
eventStartTime: "2020-07-17T18:00"
eventDoorTime: "18:00"
eventEndTime: "2020-07-25T22:00"
eventPlaceCoordinates: "43.666830666, -79.388498446"
mapCenterCoordinates: "43.666830666, -79.388498446"
mapMobileCenterCoordinates: "43.666830666, -79.388498446"

# Venue Block
venueBlockTitle: "Venue"
# This is what's called an injection :roll_eyes:
venueBigImage: '"><iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2886.0966521574587!2d-79.3942290847899!3d43.6669596595593!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x882b31005e2024cb%3A0xd92036ba603929dc!2sVictoria%20University!5e0!3m2!1sen!2sca!4v1571242908578!5m2!1sen!2sca" width="800" height="600" frameborder="0" style="border:0;" allowfullscreen=""></iframe><img src="'
venueSmallImage1: "Oldvic-victoriacollege-toronto-b-sutherland.jpg"
venueSmallImage2: "Eating_hall_victoria_college_anthony_easton.jpg"
venueSmallImage3: "911826-Medium-victoria-college-toronto-canada-canada-interior-interiorphoto-3rd-floor-classroom.jpg"
venueTitle: "Victoria University"
venueFeatures: ['Victoria University in the University of Toronto was founded in 1836 and is one of the oldest universities in Canada. It is located in downtown Toronto within easy walking distance of the Museum TTC subways station.']

# requires Tweetledee setup, see https://github.com/gdg-x/zeppelin/wiki/Initial-setup-in-_config.yml#tweets-feed

# Tweets Feed Block
tweetsFeedImage: "twitter-feed.jpg"
tweetsFeedTitle: "What's Up?"
twitterHashTag: "BioCommConf"
twitterFeed: "https://twitter.com/hashtag/BioCommConf"

# Partners Block
organizersTitle: "Organizers"
partnersTitle: "Partners"
partnersC4sponsorsButton: "Become a sponsor"

# Subscribe Block
subscribeImage: "subscribe.jpg"
subscribeTitle: "Subscribe for updates"
subscribeAction: ""
subscribeInfo: "Registration will open in late 2019. Stay tuned!"

# Tickets Block
ticketsTitle: "Price table"
ticketsInfo: "Registration grants access to all conference sections, coffee breaks, lunch and social activities. Accommodation is NOT included in the ticket price."
ticketsOffers:
 -
  name: "Early Bird"
  price: "350"
  priceCurrency: "CAD"
  ticketsNumber: "150"
  ribbon: "-5%"
  buyButtonLink: "http://dfua.ticketforevent.com/"
  buyButtonText: "Buy Now"
  ticketContentList: ["Lorem ipsum is simply", "Dummy text of the printing", "Typesetting industry"]
  validFrom: "2014-08-25T10:00"
  validThrough: "2014-09-30T23:59"
 -
  name: "Last Chance"
  price: "450"
  priceCurrency: "CAD"
  ticketsNumber: "100"
  ribbon: "-20%"
  featured: true
  buyButtonLink: "http://dfua.ticketforevent.com/"
  buyButtonText: "Buy Now"
  ticketContentList: ["Lorem ipsum is simply", "Dummy text of the printing", "Typesetting industry"]
  validFrom: "2014-10-01T00:00"
  validThrough: "2014-10-23T23:59"
  disabled: true
 -
  name: "Student"
  price: "200"
  priceCurrency: "CAD"
  ticketsNumber: "50"
  buyButtonLink: "http://dfua.ticketforevent.com/"
  buyButtonText: "Buy Now"
  additionalInfo: "Requires a valid student ID at the conference check in. Without student ID at the check in, ticket will be cancelled without refund"
  ticketContentList: ["Lorem ipsum is simply", "Dummy text of the printing", "Typesetting industry"]
  validFrom: "2014-08-20T10:00"
  validThrough: "2014-10-23T23:59"
  soldOut: false
  soldOutText: "Sold Out"

# Footer
socialLinks:
 - {link: "https://twitter.com/hashtag/BioCommConf", icon: "twitter"}
 - {link: "https://www.youtube.com/c/OBFBOSC", icon: "youtube"}
 - {permalink: "/feed.xml", icon: "rss"}
footerBlocks:
 -
  title: "Links"
  links:
   - {link: "https://www.open-bio.org/", text: "Open Bioinformatics Foundation"}
   - {link: "https://galaxyproject.org/", text: "Galaxy Community Hub"}
   - {link: "https://gccbosc2018.sched.com/", text: "GCCBOSC 2018"}
 -
  title: "Contacts"
  links:
   - {link: "mailto:bcc2020-org@lists.galaxyproject.org", text: "Email organizers"}
   - {link: "https://lists.galaxyproject.org/lists/bcc2020-interest.lists.galaxyproject.org/", text: "Sign up to get announcements"}
 -
  title: "FAQ"
  links:
   - {permalink: "/cod/", text: "Code of Conduct"}

# Blog
blogTitle: ""
# looks like we need to pay for an ad-free disqus account, disabling for now
# blogCommentsEnabled: false
# discusShortName: "devfestua"

# Speakers List Block
# https://github.com/gdg-x/zeppelin/wiki/Initial-setup-in-_config.yml#speakers-list-block
showSessions: false

# Team Block
teamBlockTitle: "About us"

# Logistics Find Way Block
findWayTitle: "Find your way here"
findWayDistance: "Distance"
findWayDriving: "DRIVING"
findWayWalking: "WALKING"
findWayBicycling: "BICYCLING"
findWayTransit: "TRANSIT"
findWayFindFlight: "Find Flight"
logisticsMapCenterCoordinates: "43.666830666, -79.388498446"
logisticsMapMobileCenterCoordinates: "43.666830666, -79.388498446"
logisticsMapAutoDirections: false

# Logistics Direction Details Block
directionDetailsImage: "location2.jpg"
directionDetailsTitle: "Toronto, Canada"
directionDetailsCards:
 - {title: "Airport", information: 'Toronto has two airports: <a href="https://www.torontopearson.com">Toronto Pearson International Airport</a> and <a href="https://www.billybishopairport.com/">Billy Bishop Toronto City Airport</a>. Take the <a href="https://www.torontopearson.com/en/transportation/up-express">UP Express</a> train from Pearson to reach downtown in 25 minutes.'}
 - {title: "Train", information: 'Toronto is served by <a href="https://www.viarail.ca">VIA Rail</a> for train connections to Canada and the USA.'}
 - {title: "By Car", information: 'Toronto is  accessible by car, about 2 hours from the border near Niagara Falls and 4 hours from Detroit. Driving and parking in downtown Toronto can be challenging due to traffic and high parking prices.'}
directionDetailsCards2:
 - {title: "Public Transit", information: 'Toronto has two transit operators: the <a href="http://www.ttc.ca/index.jsp">TTC</a> for subways, busses, and streetcars within city limits, and <a href="https://www.gotransit.com/en/">Go Transit</a> for regional busses and trains. Both services accept cash and reloadable <a href="https://www.prestocard.ca/en/">Presto Cards</a>. Victoria University is very close to the Musuem TTC subway stop.'}
 - {title: "Parking", information: '<a href="https://www.vicu.utoronto.ca/hospitality-services/overnight-accommodation/parking/">Limited parking</a> is available near Victoria University for a daily fee.'}
 - {title: "Hotels", information: 'Toronto has lots of great hotels and hostels. More information will be available later.'}
directionDetailsWideCards:
 -
  title: "Questions?"
  subCards:
   -
    title: "Hotels"
    links:
     - {link: "#", text: "A Hotel"}
   -
    title: "Registration"
    links:
     - {link: "#", text: "Registration details"}
   -
    title: "Attendance Details"
    links:
     - {link: "#", text: "Attending"}

# Hackathon
hackathonTitle: "Collaboration Fest"
enableHackathon: true

# Hackathon About Block
aboutHackathonTitle: "CollaborationFest"
hackathonRows:
 - {title: "What is it?", image: "hackathon-0.png", details: "BCC2020 will finish with CollaborationFest, a 2 (or 4) day collaborative work event where our community gathers to contribute code, documentation, training materials, and challenging analysis problems and use cases. If you are interested in learning and contributing in an intensely collaborative environment, then CollaborationFest is for you."}
 - {title: "Core and Encore", image: "hackathon-0.png", details: "CoFest is split in half again this year:<br/><b>CollaborationFest: Core: Friday & Saturday</b>: There will be lots of collaborative work, but also lots of learning about projects and software. This will be the larger of the two stages. All you need to attend this is an interest and willingness to contribute.<br/><b>CollaborationFest: Encore: Sunday & Monday</b>: The smaller (and dare we say <i>more intense</i>) of the two stages, these two days will focus on collaboration, collaboration, collaboration."}
 - {title: "Registration", image: "hackathon-0.png", details: "CollaborationFest is free, for all 4 days. You still need to register (and select either 2 or 4 days). You will need to cover some, and possibly all, of your meal expenses. Organizers will provide coffee / beverages throughout. We will attempt to get funding for as many lunches as possible."}
 - {title: "Preparing for CoFest", image: "hackathon-0.png", details: "Add or expand the cluster ideas document (coming)<br><br>Add an introduction and indicate your preferred working clusters (coming)<br><br>Ask questions on the Conference gitter channel"}

# Hackathon Location Block
hackathonLocationBlockTitle: "Location"
hackathonLocationName: "Victoria University"
hackathonLocationLink: "https://studentlife.utoronto.ca/hello/directions"
hackathonStreetAddress: "73 Queen Park's Crescent #106"
hackathonAddressLocality: "Toronto"
hackathonAddressLocalityRegion: "Ontario"
hackathonPostalCode: "M5S 1K7"
hackathonAddressCountry: "Canada"
-hackathonTimeTitle: "Coolaborate through"
hackathonStartTime: "2020-07-21T09:00"
hackathonDoorTime: "09:00"
hackathonEndTime: "2020-07-25T22:00"
viewOnMap: "View on Google Maps"
hackathonPlaceCoordinates: "43.666830666, -79.388498446"
hackathonMapCenterCoordinates: "43.666830666, -79.388498446"
hackathonMapMobileCenterCoordinates: "43.666830666, -79.388498446"

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
      logostyle: logo-light
      image_align: center
