# Plugins
plugins:
- jekyll-sitemap
- jekyll-redirect-from
safe: false
whitelist:
- jekyll-redirect-from

# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENSE.txt', 'CNAME']

# Site Settings
title: "BCC2020"
email: "bcc2020-org@lists.galaxyproject.org"
description: "BCC2020 brings together the Galaxy Community Conference and Bioinformatics Open Source Conference to meet jointly online."
baseurl: ""
url: "https://bcc2020.github.io"
permalink: "/blog/:title"
siteVerification: ""

# Head
metaKeywords: "event, bioinformatics, conference, workflows, programming, research, science, developers, toronto, bosc, galaxy"
twitterAccount: ""
socialImageSrcTwitter: ""
socialImageSrcFacebook: ""

# Navigation
navigationLinks:
 - {permalink: "/", text: "Home"}
 - {permalink: "/about/", text: "About"}
 - {permalink: "/news/", text: "News"}
 - {permalink: "/submit/", text: "Abstracts"}
 - {permalink: "/Registration/", text: "Registration"}
 - {permalink: "/schedule/", text: "Schedule"}
 - {permalink: "/training", text: "Training"}
 - {permalink: "/cofest/", text: "CoFest"}
 - {permalink: "/partners/", text: "Partners"}
bottomNavigationLinks:
 - {link: "/Registration/", text: "Registration"}
rightNavigationButtons:
 - {link: "/Registration/", text: "Registration"}

# Hero Block
heroImage: "hero.jpg"
heroTitle: "Bioinformatics Community Conference 2020"
eventDate: "July 19-21, 2020 (West) / July 20-22 (East)"
heroButtons:
 - {link: "https://galaxyproject.org/gcc/", text: "Galaxy Community Conference (GCC)", logo: "/img/organizers/galaxy_project_logo_blue.png"}
 - {link: "https://www.open-bio.org/events/bosc/", text: "Bioinformatics Open Source Conference (BOSC)", logo: "/img/organizers/bioinformatics-open-source-conference-banner.png"}

# About Block
aboutTitle: "BCC2020"
aboutUs: "BCC2020 is packed full of joint & parallel sessions, keynotes, poster & demo sessions, birds-of-a-feather, and social events. The meeting encompasses a week of activities, including two optional pre-conference training days, a three-day main meeting, and four post-meeting collaboration days. You can choose some or all of it to attend."
aboutBlock:
 - {title: "Training", image: "workshop.jpg", text: "Two dedicated days of training on all topics bioinformatics."}
 - {title: "Conference", image: "conference.jpg", text: "The main conference. Interact and share research results and ideas in open source bioinformatics and Galaxy." }
 - {title: "CoFest", image: "hackathon.jpg", text: "A two to four day unstructured session to collaboratively work on code, documentation, training materials, and challenging analysis problems and use cases." }

# About Us page
aboutUsTitle: "About BCC"
aboutUsHistory: "<p>Bioinformatics Community Conference is a combination of two existing conferences: the Bioinformatics Open Source Conference, hosted by the Open Bioinformatics Foundation, and the Galaxy Community Conference, hosted by Galaxy. The two organizations first joined forces in 2018 for GCCBOSC 2018, after noticing that there was high overlap between the communities. BCC2020 is the second joint conference, and offers opportunities for learning and networking that would not be possible in separate conferences.</p>

<p>After much consideration of the ongoing spread of COVID-19, the Organizing Committee came to the difficult decision to hold the conference online. This was deemed most socially responsible action to maintain a forum in which our community could share their work and discovery. Making this decision allows us to focus on organizing an engaging conference in this new format.</p>"

aboutVirtual: "<strong>BCC2020 will be <a href='/blog/going-virtual'>online</a>, <a href='/blog/going-global'>global</a> and <a href='/Registration/'>affordable</a>. We will be inviting our community to engage in new ways, and hope that BCC2020 will be an important space for discussion for the bioinformatics community.</strong>"

# Key Dates
keyDatesTitle: "Key Dates"
keyDatesBlock:
  - {date: "March 31 2020", thing: "Abstract submission opens"}
  - {date: "April 18 2020", thing: "Registration opens"}
  - {date: "May 8 2020", thing: "Abstract submission deadline"}
  - {date: "June 6 2020", thing: "Acceptance notifications sent to authors"}
  - {date: "July 10 2020", thing: "Early registration ends"}
  - {date: "July 17-19 2020", thing: "Training"}
  - {date: "July 19-22 2020", thing: "BCC main meeting"}
  - {date: "July 22-24 2020", thing: "CoFest: Core"}
  - {date: "July 24-26 2020", thing: "CoFest: EnCore"}

# Latest News Block
latestNewsTitle: "News"
latestNewsCount: 2

# Rockstar Speakers Block
rockstarSpeakersImage: "keynotes-bottom.jpg"
rockstarSpeakersCount: 2
rockstarSpeakersTitle: "Keynote Speakers"

# requires Tweetledee setup, see https://github.com/gdg-x/zeppelin/wiki/Initial-setup-in-_config.yml#tweets-feed

# Tweets Feed Block
tweetsFeedImage: "twitter-feed.jpg"
tweetsFeedTitle: "What's Up?"
twitterHashTag: "BioCommConf"
twitterFeed: "https://twitter.com/hashtag/BioCommConf"

# Partners Block
organizersTitle: "Organizers"
partnersTitle: "Sponsors"
partnersC4sponsorsButton: "Become a sponsor"

# Tickets Block
ticketsTitle: "Registration fees"
ticketsInfo: "There are separate registrations for training, the conference, and the CoFest events."

# Footer
socialLinks:
 - {link: "https://twitter.com/hashtag/BCC2020", icon: "twitter"}
 - {link: "https://www.youtube.com/c/OBFBOSC", icon: "youtube"}
 - {permalink: "/feed.xml", icon: "rss"}
footerBlocks:
 -
  title: "Links"
  links:
   - {link: "https://www.open-bio.org/", text: "Open Bioinformatics Foundation"}
   - {link: "https://galaxyproject.org/", text: "Galaxy Community Hub"}
   - {link: "https://gccbosc2018.sched.com/", text: "GCCBOSC 2018"}
 -
  title: "Contacts"
  links:
   - {link: "mailto:bcc2020-org@lists.galaxyproject.org", text: "Email organizers"}
   - {link: "https://lists.galaxyproject.org/lists/bcc2020-interest.lists.galaxyproject.org/", text: "Sign up to get announcements"}
 -
  title: "FAQ"
  links:
   - {permalink: "/cod/", text: "Code of Conduct"}

# Blog
# looks like we need to pay for an ad-free disqus account, disabling for now
# blogCommentsEnabled: false
# discusShortName: ""

# Speakers List Block
# https://github.com/gdg-x/zeppelin/wiki/Initial-setup-in-_config.yml#speakers-list-block
showSessions: false

# Team Block
teamBlockTitle: "The team"
teamBlockDescription: "The team behind BCC is a combination of OBF, Galaxy, OICR, Galaxy Australia and Australian BioCommons  members, along with community members that generously donate their time to review abstracts, chair sessions, and review the program."

# Scientific Program Committees
spcs:
  - "BOSC"
  - "Galaxy"


# Hackathon
hackathonTitle: "Collaboration Fest"
enableHackathon: true

# Hackathon About Block
aboutHackathonTitle: "CollaborationFest"


# Promote Block



defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
      logostyle: logo-light
      image_align: center
